export interface ICard {
  id: number;
  title: string;
  url: string;
  showCard: boolean;
  grayScale: boolean;
}

export const data: ICard[] = [
  {
    id: 0,
    title: 'Goku',
    url: '/images/card-Goku.png',
    showCard: false,
    grayScale: false,
  },
  {
    id: 12,
    title: 'Goku',
    url: '/images/card-Goku.png',
    showCard: false,
    grayScale: false,
  },
  {
    id: 1,
    title: 'Vegeta',
    url: '/images/card-Vegeta.png',
    showCard: false,
    grayScale: false,
  },
  {
    id: 13,
    title: 'Vegeta',
    url: '/images/card-Vegeta.png',
    showCard: false,
    grayScale: false,
  },
  {
    id: 2,
    title: 'Gohan',
    url: '/images/card-Gohan.png',
    showCard: false,
    grayScale: false,
  },
  {
    id: 14,
    title: 'Gohan',
    url: '/images/card-Gohan.png',
    showCard: false,
    grayScale: false,
  },
  {
    id: 3,
    title: 'Piccolo',
    url: '/images/card-Piccolo.png',
    showCard: false,
    grayScale: false,
  },
  {
    id: 15,
    title: 'Piccolo',
    url: '/images/card-Piccolo.png',
    showCard: false,
    grayScale: false,
  },
  {
    id: 4,
    title: 'Trunks',
    url: '/images/card-Trunks.png',
    showCard: false,
    grayScale: false,
  },
  {
    id: 16,
    title: 'Trunks',
    url: '/images/card-Trunks.png',
    showCard: false,
    grayScale: false,
  },
  {
    id: 5,
    title: 'Freeza',
    url: '/images/card-Freeza.png',
    showCard: false,
    grayScale: false,
  },
  {
    id: 17,
    title: 'Freeza',
    url: '/images/card-Freeza.png',
    showCard: false,
    grayScale: false,
  },
  {
    id: 6,
    title: 'Cell',
    url: '/images/card-Cell.png',
    showCard: false,
    grayScale: false,
  },
  {
    id: 18,
    title: 'Cell',
    url: '/images/card-Cell.png',
    showCard: false,
    grayScale: false,
  },
  {
    id: 7,
    title: 'Boo',
    url: '/images/card-Boo.png',
    showCard: false,
    grayScale: false,
  },
  {
    id: 19,
    title: 'Boo',
    url: '/images/card-Boo.png',
    showCard: false,
    grayScale: false,
  },
  {
    id: 8,
    title: 'Kuririn',
    url: '/images/card-Kuririn.png',
    showCard: false,
    grayScale: false,
  },
  {
    id: 20,
    title: 'Kuririn',
    url: '/images/card-Kuririn.png',
    showCard: false,
    grayScale: false,
  },
  {
    id: 9,
    title: 'Satan',
    url: '/images/card-Satan.png',
    showCard: false,
    grayScale: false,
  },
  {
    id: 21,
    title: 'Satan',
    url: '/images/card-Satan.png',
    showCard: false,
    grayScale: false,
  },
  {
    id: 10,
    title: 'Kame',
    url: '/images/card-Kame.png',
    showCard: false,
    grayScale: false,
  },
  {
    id: 22,
    title: 'Kame',
    url: '/images/card-Kame.png',
    showCard: false,
    grayScale: false,
  },
  {
    id: 12,
    title: 'Chichi',
    url: '/images/card-Chichi.png',
    showCard: false,
    grayScale: false,
  },
  {
    id: 23,
    title: 'Chichi',
    url: '/images/card-Chichi.png',
    showCard: false,
    grayScale: false,
  },
];
